name: Check
on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - "**/docs/**/*.mdx"
      - "**/docs/**/*.md"
      - "**/*.mdx"
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/docs/**/*.mdx"
      - "**/docs/**/*.md"
      - "**/*.mdx"
      - "**/*.md"
      - "**/*.yml"
jobs:
  check:
    name: Format, lint, typecheck, build, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: bun install
      - name: Format
        run: bun run format:check
      - name: Lint
        run: bun run lint
      - name: Typecheck
        run: bun run typecheck
      - name: Build
        run: bun run build
      - name: Test
        run: bun test
