name: Check
on: [push]
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Setup
        run: bun run setup
      - name: Build
        run: bun run build
      - name: Test
        run: bun test
